# Generated by Django 3.1.5 on 2021-01-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagehandler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagehandler',
            name='low_res_image',
        ),
    ]
